import  { existsSync, readFileSync, writeFileSync } from "fs";
import { parse } from "json5";
import { request } from "https";
import { randomBytes } from "crypto";
import { on } from "events";
import { config as loadEnv } from "dotenv";

loadEnv({ quiet: true });

export interface ITrasnlationEntry {
    key: string;
    english: string;
    translation: string;
}
export interface ICommentInfo {
  key: string;
  comment: string;
  position: 'top' | 'right';
}
export interface IKeyCommentInfo {
  commentTop?: string;
  commentRight?: string;
}
type KeyCommentHash = { [key: string]: IKeyCommentInfo };
export interface IStringToTranslate { 
  text: string;
  keys: string[];
  translation?: string; 
 };

const autoGeneratedPrefix = "[Auto-translated]";
const endpoint = "api.cognitive.microsofttranslator.com";
const resource_region = "southcentralus";

let translationKey = "";

/**
 * Sets the Azure Translator subscription key for this process, ahead of the
 * TRANSLATION_API_KEY environment variable. Pass an empty string to fall back to it.
 */
export function setTranslationKey(key: string): void {
  translationKey = key || "";
}

function getTranslationKey(): string {
  const key = translationKey || process.env.TRANSLATION_API_KEY;
  if (!key) {
    throw new Error("No translator subscription key. Pass it as `survey-utils translate <product> --key <key>`, "
      + "or set TRANSLATION_API_KEY in the environment or in .env (copy .env.example).");
  }
  return key;
}

function UUIDGenerator() {
  return randomBytes(16).toString("hex");
}

export class LocalizationUtils {
  public translateFile(fileName: string, englishJSON: any, englishComments?: Array<ICommentInfo>): void {
    const text = this.readFile(fileName);
    const onComplete = (newText: string): void => {
      if(newText && newText !== text) {
        writeFileSync(this.getTranslationFileName(fileName), newText, "utf8");
        this.reportMessage("Translated: " + fileName);
      }
    }
    this.translateText(text, englishJSON, onComplete, fileName, englishComments);
  }
  public translateText(text: string, englishJSON: any, onComplete: (newText: string) => void, fileName: string, englishComments?: Array<ICommentInfo>): void {
    const locale = this.getMSTranslationLocale(text);
    if (locale === "en") {
      onComplete("");
      return;
    }
    if (!locale) {
      this.reportMessage("MS translator doesn't support: " + fileName + ".");
      onComplete("");
      return;
    }
    const stringsToTranslate = this.getStringsToTranslate(text, englishJSON);
    if (stringsToTranslate.length === 0) {
      if (!this.updateFile(fileName, englishJSON)) {
        this.reportMessage("No strings to translate or remove in " + fileName + ".");
      }
      return;
    }
    const onCompleteTranslation = () => {
      const newJsonText = this.getJsonWithTranslation(text, englishJSON, stringsToTranslate, englishComments);
      onComplete(this.replaceJson(text, newJsonText));
    };
    this.translateStrings(locale, stringsToTranslate, onCompleteTranslation);
  }
  public updateFile(fileName: string, englishJSON: any): boolean {
    const text = this.readFile(fileName);
    const newText = this.updateTranslatedText(text, englishJSON);
    const res = text !== newText;
    if (res) {
      writeFileSync(this.getTranslationFileName(fileName), newText, "utf8");
      this.reportMessage("Updated, un-needed strings were removed: " + fileName);
    }
    return res;
  }
  public updateTranslatedText(text: string, englishJSON: any): string {
    const json = this.getJson(text);
    const comments = this.readJsonComments(text);
    const newJSON = this.removeUnusedKeys(json, englishJSON);
    const newJsonText = this.generateJsonText(newJSON, comments, 2);
    return this.replaceJson(text, newJsonText);
  }
  public translateStrings(locale: string, stringsToTranslate: IStringToTranslate[], onComplete: () => void): void {
    if (locale === "en") {
      onComplete();
      return;
    }
    const translationKey = getTranslationKey();
    const dataToTranslate = [];
    for (let i = 0; i < stringsToTranslate.length; i ++) {
      dataToTranslate.push({ text: stringsToTranslate[i].text });
    }
    let data = "";
    request({
      hostname: endpoint,
      path: "/translate?api-version=3.0&from=en&to=" + locale,
      method: "POST",
      headers: {
        "Ocp-Apim-Subscription-Key": translationKey,
        "Ocp-Apim-Subscription-Region": resource_region,
        "Content-type": "application/json",
        "X-ClientTraceId": UUIDGenerator()
      }
    }, (response) => {
      response.on("data", function (chunk) {
        data += chunk;
      });
      response.on("end", function () {
        const translations = JSON.parse(data);
        for (let i = 0; i < translations.length; i ++) {
          const item = translations[i];
          const tr_item = stringsToTranslate[i];
          tr_item.translation = item.translations[0].text;
        }
        onComplete();
      });
    }).on("error", (error) => {
      this.reportMessage("Error to translate: " + locale + ". Error: " + JSON.stringify(error, null, 2));
    }).end(JSON.stringify(dataToTranslate));

  }
  public getTranslationFileName(name: string): string {
    if (name.indexOf(".ts") < 0) {
      name += ".ts";
    }
    return name;
  }
  public readFile(fileName: string): string {
    return readFileSync(this.getTranslationFileName(fileName), "utf8");
  }
  public readJsonComments(code: string):  ICommentInfo[] {
    return new JsonHandler().collectComments(code);
  }
  public removeEnglishUnneededComments(fileName: string): void {
    const text = this.readFile(fileName);
    const json = this.getJson(text);
    const comments = this.readJsonComments(text);
    const commentHash = this.getJsonKeyCommentsHash(comments);
    for (const key in commentHash) {
      const obj = commentHash[key];
      if (!!obj.commentTop) {
        const val = this.getValueByKey(json, key);
        if (obj.commentTop.startsWith(autoGeneratedPrefix)
          || !!val && obj.commentTop.startsWith("\"") && JSON.parse(obj.commentTop).trim() === val.trim()) {
          delete obj.commentTop;
        }
      }
    }
    const newText = new JsonTextGenerator().generate(this.getJson(text), commentHash, 2);
    writeFileSync(this.getTranslationFileName(fileName), this.replaceJson(text, newText), "utf8");
  }
  private getJsonKeyCommentsHash(comments: ICommentInfo[]): KeyCommentHash {
    const hash: KeyCommentHash = {};
    comments.forEach(comment => {
      const obj: IKeyCommentInfo = hash[comment.key] || {};
      if (obj.commentTop === undefined && comment.position === 'top') {
        obj.commentTop = comment.comment;
      }
      if (obj.commentRight === undefined && comment.position === 'right') {
        obj.commentRight = comment.comment;
      }
      if (!hash[comment.key]) {
        hash[comment.key] = obj;
      }
    });
    return hash;
  }
  public replaceJson(code: string, newJson: string): string {
    const jsonHandler = new JsonHandler();
    return jsonHandler.replaceJson(code, newJson);
  }
  public getJson(code: string): any {
    const jsonHandler = new JsonHandler();
    return parse(jsonHandler.getJson(code));
  }
  public getStringsToTranslate(translationText: string, englishJSON: any): IStringToTranslate[] {
    const commentHash = this.getJsonKeyCommentsHash(this.readJsonComments(translationText));
    const json = this.getJson(translationText);
    const resultHash: { [key: string]: string[] } = {};
    const processStr = (str: string): string => {
      const res = str.replace(autoGeneratedPrefix, "").trim();
      if (res.startsWith("\"") && res.endsWith("\"")) return JSON.parse(res);
      return res;
    }
    const collect = (trJson: any, enJson: any, path: string): void => {
      Object.keys(enJson).forEach(key => {
        if (key.startsWith("license")) return; // Skip license keys
        const fullPath = path ? `${path}.${key}` : key;
        let enObj = enJson[key];
        if (typeof enObj === 'object') {
          collect(trJson[key] || {}, enObj, fullPath);
        } else {
          const hasValue = trJson[key] !== undefined;
          if (hasValue) {
            let topComment = commentHash[fullPath]?.commentTop || "";
            const isAutoTranslated = topComment.startsWith(autoGeneratedPrefix);
            if (topComment) {
              topComment = processStr(topComment);
            }
            if (isAutoTranslated) {
              if (topComment === enObj) return; // Auto-translated and up-to-date
            } else {
              if (trJson[key] !== enObj) return; // Manually translated to a different value
            }
          }
          if (!resultHash[enObj]) {
            resultHash[enObj] = [];
          }
          resultHash[enObj].push(fullPath);
        }
      });
    };
    collect(json, englishJSON, "");
    const result: IStringToTranslate[] = [];
    Object.keys(resultHash).forEach(key => {
      result.push({ text: key, keys: resultHash[key] });
    });
    return result;
  }
  public getJsonWithTranslation(translationText: string, englishJSON: any, stringsToTranslate: IStringToTranslate[], englishComments?: ICommentInfo[]): string {
    const commentHash = this.getJsonKeyCommentsHash(this.readJsonComments(translationText));
    englishComments?.forEach(entry => {
      const obj = commentHash[entry.key] || {};
      if (commentHash[entry.key] === undefined) {
        commentHash[entry.key] = obj;
      }
      if (entry.position === 'top' && !obj.commentTop) {
        obj.commentTop = entry.comment;
      }
      if (entry.position === 'right' && !obj.commentRight) {
        obj.commentRight = entry.comment;
      }
    });
    const englishTopComments: { [key: string]: string } = this.getEnglishTopComments(englishJSON);
    for (let key in englishTopComments) {
      const obj = commentHash[key] || {};
      if (commentHash[key] === undefined) {
        commentHash[key] = obj;
      }
      if (!obj.commentTop) {
        obj.commentTop = "\"" + englishTopComments[key] + "\"";
      }
    }
    const json = this.getJson(translationText);
    stringsToTranslate.forEach(entry => {
      if (entry.translation) {
        entry.keys.forEach(key => {
          this.setNewValue(json, key, entry.translation);
          const obj = commentHash[key] || {};
          obj.commentTop = autoGeneratedPrefix + " " + JSON.stringify(entry.text);
          commentHash[key] = obj;
        });
      }
    });
    const newJson = this.removeUnusedKeys(json, englishJSON);
    return new JsonTextGenerator().generate(newJson, commentHash, 2);
  }
  getEnglishTopComments(englishJSON: any): { [key: string]: string; } {
    const result: { [key: string]: string; } = {};
    const collect = (obj: any, path: string) => {
      Object.keys(obj).forEach(key => {
        const fullPath = path ? `${path}.${key}` : key;
        const value = obj[key];
        if (typeof value === 'object') {
          collect(value, fullPath);
        } else {
          result[fullPath] = value;
        }
      });
    };
    collect(englishJSON, "");
    return result;
  }
  public generateJsonText(json: any, comments: ICommentInfo[], padding: number = 2): string {
    return new JsonTextGenerator().generate(json, this.getJsonKeyCommentsHash(comments), padding);
  }
  private getMSTranslationLocale(text: string): string | undefined {
    const locale = this.getLocale(text);
    if (locale === "gr") return "el";
    if (locale === "ua") return "uk";
    if (locale === "tel") return "te";
    if (locale === "rs") return "sr-Latn";
    if (locale === "tg") return undefined; // "tg" is not supported by MS
    return locale;
  }
  private getLocale(text: string): string | undefined {
    let subStr = "localeCode: \"";
    let index = text.indexOf(subStr);
    if (index < 0) subStr = "getLocaleStrings(\"";
    index = text.indexOf(subStr);
    if (index < 0) return undefined;
    index += subStr.length;
    const endIndex = text.indexOf("\"", index);
    if (endIndex < 0) return undefined;
    return text.substring(index, endIndex);
  }
  private setNewValue(json: any, key: string, value?: string): void {
    if (!value) return;
    const parts = key.split('.');
    let current = json;
    for (let i = 0; i < parts.length - 1; i++) {
      if (current[parts[i]] === undefined) {
        current[parts[i]] = {};
      }
      current = current[parts[i]];
      if (!current || typeof current !== 'object') return;
    }
    current[parts[parts.length - 1]] = value;
  }
  private getValueByKey(json: any, key: string): any {
    const parts = key.split('.');
    let current = json;
    for (let i = 0; i < parts.length; i++) {
      current = current[parts[i]];
      if (!current) return undefined;
    }
    return current;
  }
  private removeUnusedKeys(json: any, englishJson: any): any {
    const result: any = {};
    Object.keys(englishJson).forEach(key => {
      if (json[key] !== undefined) {
        if (typeof json[key] === 'object' && typeof englishJson[key] === 'object') {
          result[key] = this.removeUnusedKeys(json[key], englishJson[key]);
        } else {
          result[key] = json[key];
        }
      }
    });
    return result;
  }
  private reportMessage(msg: string): void {
    // eslint-disable-next-line
    console.log(msg);
  }
}

class JsonTextGenerator {
  generate(json: any, commentHash: KeyCommentHash, padding: number = 2): string {
    const isNeedToStringify = (str: string): boolean => {
      if (str === "true" || str === "false" || str === "null") return true;
      return !/^[a-zA-Z_$][0-9a-zA-Z_$]*$/.test(str);
    };
    const buildObject = (obj: any, path: string, level: number): string => {
      const indent = ' '.repeat(level * padding);
      const innerIndent = ' '.repeat((level + 1) * padding);
      const propStrings: string[] = [];
      Object.keys(obj).forEach((key, index, array) => {
        const fullPath = path ? `${path}.${key}` : key;
        const commentKey = commentHash[fullPath] || {};
        const topComment = commentKey.commentTop ? [`${innerIndent}// ${commentKey.commentTop}`] : "";

        const rightCommentStr = commentKey.commentRight ? ` // ${commentKey.commentRight}` : '';

        let valStr: string;
        const val = obj[key];
        if (typeof val === 'object' && val !== null) {
          valStr = buildObject(val, fullPath, level + 1);
        } else {
          valStr = JSON.stringify(val);
        }

        const keyStr = isNeedToStringify(key) ? JSON.stringify(key) : key;
        const comma = index < array.length - 1 ? ',' : '';
        const propLine = `${innerIndent}${keyStr}: ${valStr}${comma}${rightCommentStr}`;
        if (!!topComment) {
          propStrings.push(topComment + '\n' + propLine);
        } else {
          propStrings.push(propLine);
        }
      });
      const props = propStrings.join('\n');
      return `{\n${props}\n${indent}}`;
    };

    return buildObject(json, '', 0);
  }
}

class JsonHandler {
  private findExportStart(code: string): number {
    let i = 0;
    const len = code.length;

    const skipWhitespace = () => {
      while (i < len && /\s/.test(code[i])) i++;
    };

    while (i < len) {
      skipWhitespace();
      if (code.substr(i, 6) === 'export') {
        i += 6;
        skipWhitespace();
        // Skip var/let/const
        if (code.substr(i, 5) === 'const') {
          i += 5;
        } else if (code.substr(i, 3) === 'let' || code.substr(i, 3) === 'var') {
          i += 3;
        } else {
          continue;
        }
        skipWhitespace();
        // Skip variable name
        while (i < len && /[a-zA-Z0-9_$]/.test(code[i])) i++;
        skipWhitespace();
        if (code[i] === '=') {
          i++;
          skipWhitespace();
          if (code[i] === '{') {
            return i;
          }
        }
      } else {
        i++;
      }
    }
    throw new Error('No exported object found');
  }

  private findObjectEnd(code: string, start: number): number {
    let i = start + 1; // skip {
    const len = code.length;
    let depth = 1;
    while (i < len && depth > 0) {
      if (/\s/.test(code[i])) {
        i++;
      } else if (code[i] === '/' && code[i + 1] === '/') {
        i += 2;
        while (i < len && code[i] !== '\n' && code[i] !== '\r') i++;
        if (code[i] === '\r') i++;
        if (code[i] === '\n') i++;
      } else if (code[i] === '"' || code[i] === "'") {
        let quote = code[i];
        i++;
        while (i < len) {
          if (code[i] === '\\') {
            i += 2;
            continue;
          }
          if (code[i] === quote) {
            i++;
            break;
          }
          i++;
        }
      } else if (code[i] === '{') {
        depth++;
        i++;
      } else if (code[i] === '}') {
        depth--;
        i++;
      } else {
        i++;
      }
    }
    if (depth !== 0) {
      throw new Error('Unmatched braces');
    }
    return i;
  }

  public getJson(code: string): string {
    const start = this.findExportStart(code);
    const end = this.findObjectEnd(code, start);
    return code.substring(start, end);
  }

  public replaceJson(code: string, newJson: string): string {
    const start = this.findExportStart(code);
    const end = this.findObjectEnd(code, start);
    return code.substring(0, start) + newJson + code.substring(end);
  }

  public collectComments(code: string): ICommentInfo[] {
    const result: ICommentInfo[] = [];
    const start = this.findExportStart(code);
    let i = start;
    const len = code.length;

    const skipWhitespace = () => {
      while (i < len && /\s/.test(code[i])) i++;
    };

    const skipSpace = () => {
      while (i < len && (code[i] === ' ' || code[i] === '\t')) i++;
    };

    const skipComment = (): string | null => {
      if (code[i] === '/' && code[i + 1] === '/') {
        i += 2;
        skipSpace();
        let s = i;
        while (i < len && code[i] !== '\n' && code[i] !== '\r') i++;
        let comment = code.substring(s, i).trim();
        if (code[i] === '\r') i++;
        if (code[i] === '\n') i++;
        return comment;
      }
      return null;
    };

    const parseString = (): string => {
      let quote = code[i];
      i++;
      let s = i;
      let str = '';
      while (i < len) {
        if (code[i] === '\\') {
          str += code.substring(s, i);
          i++;
          if (i < len) {
            str += code[i];
            i++;
          }
          s = i;
        } else if (code[i] === quote) {
          str += code.substring(s, i);
          i++;
          return str;
        } else {
          i++;
        }
      }
      throw new Error('Unterminated string');
    };

    const parseValue = (): 'object' | 'string' => {
      skipWhitespace();
      if (code[i] === '{') {
        return 'object';
      } else if (code[i] === '"' || code[i] === "'") {
        parseString();
        return 'string';
      } else {
        throw new Error('Unexpected value, expected object or string');
      }
    };

    const parseObject = (currentPath: string) => {
      skipWhitespace();
      if (code[i] !== '{') throw new Error('Expected {');
      i++; // skip {
      while (true) {
        skipWhitespace();
        let leadingComments: string[] = [];
        let comment: string | null;
        while ((comment = skipComment())) {
          if (comment) leadingComments.push(comment);
        }
        skipWhitespace();
        if (code[i] === '}') {
          i++;
          break;
        }
        // Parse key
        let key: string;
        if (code[i] === '"' || code[i] === "'") {
          key = parseString();
        } else {
          let s = i;
          while (i < len && /[a-zA-Z0-9_$]/.test(code[i])) i++;
          key = code.substring(s, i);
          if (!key) continue; // skip empty keys
        }
        let fullPath = currentPath ? currentPath + '.' + key : key;
        skipWhitespace();
        if (code[i] !== ':') throw new Error('Expected :');
        i++; // skip :
        const valueType = parseValue();
        if (valueType === 'object') {
          parseObject(fullPath);
        }
        
        // Look for trailing comment (same line)
        skipSpace();
        // Check if there's a comma first, then look for comment
        let hasComma = false;
        if (code[i] === ',') {
          hasComma = true;
          i++; // skip comma
          skipSpace(); // skip spaces after comma
        }
        let trailingComment = skipComment();
        
        // Add comments to result
        leadingComments.forEach(c => {
          result.push({ key: fullPath, comment: c, position: 'top' });
        });
        if (trailingComment) {
          result.push({ key: fullPath, comment: trailingComment, position: 'right' });
        }
        
        skipWhitespace();
        if (code[i] === '}') {
          i++;
          break;
        } else if (!hasComma && code[i] === ',') {
          i++;
        } else if (hasComma) {
          // Comma already processed above
        } else {
          throw new Error('Expected , or }');
        }
      }
    };

    parseObject('');
    return result;
  }
}